/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Exchange a Firebase identity token */
    post: operations['login_v1_auth_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Check API health */
    get: operations['health_v1_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ErrorDetail */
    ErrorDetail: {
      /** Code */
      code: string;
      /** Details */
      details: {
        [key: string]: unknown;
      };
      /** Message */
      message: string;
    };
    /** ErrorResponse */
    ErrorResponse: {
      error: components['schemas']['ErrorDetail'];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Service */
      service: string;
      /**
       * Status
       * @constant
       */
      status: 'ok';
      /** Version */
      version: string;
    };
    /** LoginRequest */
    LoginRequest: {
      /** Firebase Id Token */
      firebase_id_token: string;
    };
    /** LoginResponse */
    LoginResponse: {
      /** Access Token */
      access_token: string;
      /** Expires In */
      expires_in: number;
      /** Onboarding Complete */
      onboarding_complete: boolean;
      /** Refresh Token */
      refresh_token: string;
      user: components['schemas']['UserResponse'];
    };
    /** SocialIdentityResponse */
    SocialIdentityResponse: {
      /** Profile Url */
      profile_url: string;
      /**
       * Provider
       * @constant
       */
      provider: 'threads';
      /** Username */
      username: string;
    };
    /** UserResponse */
    UserResponse: {
      /** Display Name */
      display_name: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Is Retired */
      is_retired: boolean;
      social_identity: components['schemas']['SocialIdentityResponse'] | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  login_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LoginResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  health_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
}
